apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.name }}-operator
  name: {{ .Values.name }}-operator
  namespace: {{ .Release.Namespace }}
data:
  NAMESPACE: {{ .Release.Namespace }}
  CI_OPERATOR_IMAGE: {{ .Release.images.ci }}
  {{- with .Values.operConfigmap }}
  {{- toYaml . | nindent 2 }}
  {{- end }}