{{- if (default .Values.oidc.enable false)}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: oidc
  name: oidc
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AUTH0_CLIENT_SECRET: your_password
{{- end }}