apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}-operator
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}-operator
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccount: {{ .Values.name }}-sa
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ .Values.name }}-web
        - name: rbac
          configMap:
            name: {{ .Values.name }}-rbac
            optional: true
      containers:        
        - name: operator
          image: {{ .Values.images.ci }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ template "operPort" . }}
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}-operator
          env:
            {{- include "cilab.operEnv" . | nindent 12 }}
          volumeMounts:
            - name: rbac
              mountPath: /rbac
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ template "operPort" . }}
            initialDelaySeconds: 5
            periodSeconds: 15
        - name: redis
          image: {{ .Values.images.redis }}
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 15
        - name: web
          image: {{ .Values.images.web }}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - cp -L /nginx-conf/nginx-conf.conf /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /nginx-conf
        - name: ws
          image: {{ .Values.images.ws }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ template "wsPort" . }}
          env:
            {{- include "cilab.wsEnv" . | nindent 12 }}
        - name: cron
          image: {{ .Values.images.ci }}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["while true; ./cron-ci;do sleep 10; done;"]
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}-operator
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: TZ
              value: {{ .Values.timezone | quote }}