apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.name }}-web
  name: {{ .Values.name }}-web
  namespace: {{ .Release.Namespace }}
data:
  {{- include "cilab.webCfg" . | nindent 2 }}