name: ci-lab
images:
  ci: public.ecr.aws/w9d5y7i2/ci-operator:v1.5.0
  web: public.ecr.aws/w9d5y7i2/ci-web:v1.4.0
  ws: public.ecr.aws/w9d5y7i2/ci-ws:v1.1.0
  redis: public.ecr.aws/docker/library/redis:7.2.5-bookworm
  git: public.ecr.aws/w9d5y7i2/alpine/git:2.45.2@sha256:498fd5ec2ab64142a6c2e64737b24585d5c69c69f1c8a145babb1efef42b21d9
  default: busybox:latest
saAnnotations:
imagePullSecrets:
nodeSelector:
tolerations:
affinity:
operConfigmap:
  ACCESS_ORIGIN: "*"
  JOB_BACKOFF_LIMIT: "0"
  CI_OPERATOR_NAME: ci-lab-operator
  LOG_CONTAINER_NAME: runner
  LOG_TIME_SINCE: 10s
  INITIAL_ADMIN_USER: admin
  GIT_SRC_PATH: "/git-src"
ingress:
  enable: false
  annotations:
    nginx.ingress.kubernetes.io/client-max-body-size: '0'
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
  spec:
    ingressClassName: nginx
    rules:
      - host: cilab.site.my
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: ci-lab-operator
                  port:
                    number: 80
oidc:
  enable: false
  config: |
    {
      "auth0": {
        "clientId": "auth0_clientId",
        "clientSecret": "OIDC_CLIENT_SECRET",
        "authorizeUrl": "https://cilab-test.auth0.com/oauth/authorize",
        "tokenUrl": "https://cilab-test.auth0.com/oauth/token",
        "redirectUrl": "http://localhost:3000/api/callback/auth0",
        "scopes": ["openid","profile","email","offline_access"],
        "state": "",
        "user": {
          "method": "GET",
          "endpoint": "https://cilab-test.auth0.com/userinfo",
          "headers": {
            "Accept": "application/json"
          }
        },
        "mappingUser": {
          "userId": "$nickname",
          "oidcId": "$email",
          "username": "$nickname",
          "name": "$name",
          "email": "$email",
          "sub": "$sub"
        },
        "info":{
          "name": "CILab Auth0",
          "description": "Auth0 OIDC",
          "sort": 1,
          "logo": "logo-auth0.png",
          "hint": "Enter your Email"
        },
        "logoutUrl": "https://cilab-test.auth0.com/v2/logout?client_id=auth0_clientId&returnTo=http://localhost:3000/logout-result"
      }
    }
timezone: Asia/Bangkok
OIDC_CLIENT_SECRET: ""