name: ci-lab
images:
  ci: amdmanzero/ci-operator:v1.4.0@sha256:5a512f41c25e712560690d4b63681a39901ad70653dad89832a19f3a0507590b
  web: amdmanzero/ci-web:v1.3.0@sha256:a1a0a5135785e75f5fb64c5a6dd0382ffdf5d5ec1babe8d2f9154b481e5afbf2
  ws: amdmanzero/ci-ws:v1.0.0@sha256:f00e443ed266ba70df57364949f4043516af7d905111174c4f8377fd2d4a47b0
  redis: redis:7.2.5-bookworm@sha256:e422889e156ebea83856b6ff973bfe0c86bce867d80def228044eeecf925592b
  git: alpine/git:2.43.0
  default: busybox:latest
saAnnotations:
imagePullSecrets:
nodeSelector:
tolerations:
affinity:
operConfigmap:
  ACCESS_ORIGIN: "*"
  JOB_BACKOFF_LIMIT: "0"
  CI_OPERATOR_NAME: ci-lab-operator
  LOG_CONTAINER_NAME: runner
  LOG_TIME_SINCE: 10s
  INITIAL_ADMIN_USER: admin
  GIT_SRC_PATH: "/git-src"
ingress:
  enable: false
  annotations:
    nginx.ingress.kubernetes.io/client-max-body-size: '0'
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
  spec:
    ingressClassName: nginx
    rules:
      - host: cilab.site.my
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: ci-lab-operator
                  port:
                    number: 80
oidc:
  enable: false
  config: |
    {
      "auth0": {
        "clientId": "auth0_clientId",
        "clientSecret": "AUTH0_CLIENT_SECRET",
        "authorizeUrl": "https://cilab-test.auth0.com/oauth/authorize",
        "tokenUrl": "https://cilab-test.auth0.com/oauth/token",
        "redirectUrl": "http://localhost:3000/api/callback/auth0",
        "scopes": ["openid","profile","email","offline_access"],
        "state": "",
        "user": {
          "method": "GET",
          "endpoint": "https://cilab-test.auth0.com/userinfo",
          "headers": {
            "Accept": "application/json"
          }
        },
        "mappingUser": {
          "userId": "$nickname",
          "oidcId": "$email",
          "username": "$nickname",
          "name": "$name",
          "email": "$email",
          "sub": "$sub"
        },
        "info":{
          "name": "CILab Auth0",
          "description": "Auth0 OIDC",
          "sort": 1,
          "logo": "logo-auth0.png",
          "hint": "Enter your Email"
        },
        "logoutUrl": "https://cilab-test.auth0.com/v2/logout?client_id=auth0_clientId&returnTo=http://localhost:3000/logout-result"
      }
    }
timezone: Asia/Bangkok